/****** Script SQL ******/
--Base de datos
CREATE DATABASE [TempHumedad-HiriartCorales]
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET ARITHABORT OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET RECOVERY FULL 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET  MULTI_USER 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET  READ_WRITE 
GO


--Tabla
USE [TempHumedad-HiriartCorales]

CREATE TABLE FechaTempHumedad(
	RegistroID int IDENTITY(1,1) NOT NULL primary key,
	FechaHora datetime NOT NULL,
	Temperatura float NOT NULL,
	Humedad float NOT NULL,
);
GO
