USE [master]
GO

/****** Object:  Database [TempHumedad-HiriartCorales]    Script Date: 2/7/2021 21:18:33 ******/
CREATE DATABASE [TempHumedad-HiriartCorales]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TempHumedad-HiriartCorales', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVERDEV\MSSQL\DATA\TempHumedad-HiriartCorales.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TempHumedad-HiriartCorales_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVERDEV\MSSQL\DATA\TempHumedad-HiriartCorales_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TempHumedad-HiriartCorales].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET ARITHABORT OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET RECOVERY FULL 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET  MULTI_USER 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TempHumedad-HiriartCorales] SET  READ_WRITE 
GO

/****** Object:  Table [dbo].[FechaTempHumedad]    Script Date: 2/7/2021 21:19:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FechaTempHumedad](
	[IDRegistro] [int] IDENTITY(1,1) NOT NULL,
	[FechaHora] [datetime] NOT NULL,
	[Temperatura] [float] NOT NULL,
	[Humedad] [float] NOT NULL,
 CONSTRAINT [PK_FechaTempHumedad] PRIMARY KEY CLUSTERED 
(
	[IDRegistro] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO